### ISSUE TITLE
Ho i can compute crc by hex?

### ISSUE THREAD

**Issue by averichev** [pburggraf/CRC#1]
Ho i can compute crc by hex?

Like this https://crccalc.com/?crc=011A9461005900&method=crc8&datatype=hex

(Radio button ***hex*** checked)

@pburggraf ?

**Comment by pburggraf** [comment]
Hi @averichev,

you can convert the hexadecimal value to a binary string with the internal function "hex2bin".
Here is a quick example which generates the same result as crccaclc:
```
<?php

require __DIR__ . '/vendor/autoload.php';

$crc8 = new \PBurggraf\CRC\CRC8\CRC8();

// Should return string(4) "0x84"
var_dump('0x' . dechex($crc8->calculate(hex2bin('011A9461005900'))));
```

I hope this solves your problem.

**Comment by averichev** [comment]
Thank you so much and thank you for this library.
