### ISSUE TITLE
Integrating phpstan/phpstan during Travis CI build

### ISSUE THREAD

**Issue by peter279k** [pburggraf/CRC#3]
See this [issue](https://github.com/pburggraf/BinaryUtilities/issues/3).

**Comment by pburggraf** [comment]
Hey there,
first of all, thank you for your suggestion!

But it seems that phpstan is already implemented in the travis build. See .travis.yml line 15.
Do you have any further suggestions or improvements to this?

**Comment by peter279k** [comment]
Yes. That's great and I think I don't look at that line on `.travis.yml` file :).

Closed.
