### ISSUE TITLE
Package gets identified as phpstan-extension

### ISSUE THREAD

**Issue by sebastiandeppisch** [pburggraf/CRC#7]
I am using phpstan/extension-installer to autoload all phpstan extensions. It tries to find a phpstan extension file in this package: 
```
./vendor/bin/phpstan analyse
Note: Using configuration file /path/to/project/phpstan.neon.
Config file /path/to/project/vendor/pburggraf/crc/extension.neon does not exist or isn't readable
```
According to https://github.com/phpstan/extension-installer#instructions-for-extension-developers I think, you should remove the following part from your composer.json:

```
 "extra": {
    "phpstan": {
      "includes": [
        "extension.neon"
      ]
    }
  }
  ```

**Comment by pburggraf** [comment]
Hey there,

thank you for reporting this bug.
The newly tagged version does not include the shown part in the composer.json anymore.

I hope this solves your problem.
