### ISSUE TITLE
Multiple performance issues in the library

### ISSUE THREAD

**Issue by BafS** [pburggraf/CRC#8]
There is some serious performance issues in the library

1. The lookup table is generated in the constructor, this slows down the instantiation of a class, the constructor should not have heavy logic and it would be much better to use dependency injection and pass the lookup table as an argument.
2. The lookup table is never used (!), there is a table generation for literally nothing as we don't rely on the lookup table at all to generate CRCs

Those issues make the library way slower than it should be, for nothing. Either the lookup table should be removed from the constructor, either it should be used later on (but I dislike the idea of generating a table to then use it, it doesn't make sense) or better: we can inject the lookup table to speed up calculation, if not it will rely on the current implementation.

**Comment by pburggraf** [comment]
Thanks for reporting the problems!
I will take a look and try to develop a speed up fix without breaking any existing implementation. 

If the table is really not used, it surly can be removed completely.
But if I remember correct I had a case where the table was actually needed.

**Comment by pburggraf** [comment]
I have now pushed a fix for the problem.
The method "calculate" can be used as before and still calculates internally without a lookup table.

But since there was a special case where it needs a broken/customized lookup table, I created a way to calculate it beforehand. This can be passed as a parameter to the method "calculateWithTable".

Here is an example:
```PHP
$spiCrc = new \PBurggraf\CRC\CRC16\SpiFujitsu();
var_dump(dechex($spiCrc->calculate('35'))); // string(4) "b2f0"

$spiCrcWithTable = new \PBurggraf\CRC\CRC16\SpiFujitsu();
// now you can pre-populate the lookup table
$table = $spiCrcWithTable->populateTable();
// or manipulate the table
$table[0xFF] = 0;
var_dump(dechex($spiCrcWithTable->calculateWithTable('35', $table))); // string(4) "ac00"
```

**Comment by BafS** [comment]
Thanks for your hard work! It's great to see it fixed and it will positively impact apps using this lib.

In the meantime I went ahead and did my own library with an other architecture in mind, to simplify things and use composition over inheritance: https://github.com/BafS/crc-php
